
import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: "Robe d'été florale",
    description: "Une robe d'été légère et aérée avec un magnifique motif floral. Parfaite pour les journées ensoleillées. Fabriquée en coton 100% biologique.",
    price: 25000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757878/allano-app/floral-summer-dress_vj2gld.jpg', 'https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/floral-summer-dress-2_tqz1vj.jpg', 'https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/floral-summer-dress-3_zgrfld.jpg'],
    category: 'Vêtements',
    subcategory: 'Robes',
    brand: 'Allano Chic',
    rating: 4.5,
    reviews: 120,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Bleu Ciel', hex: '#87CEEB' },
      { name: 'Rose Pâle', hex: '#FFD1DC' },
    ],
    isNew: true,
  },
  {
    id: 'prod_002',
    name: 'T-shirt en coton bio',
    description: "Un t-shirt basique et doux, essentiel à toute garde-robe. Fabriqué en coton 100% biologique certifié.",
    price: 18000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/organic-cotton-tshirt_hgxvpr.jpg', 'https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/organic-cotton-tshirt-2_y2a5r9.jpg'],
    category: 'Vêtements',
    subcategory: 'T-shirts',
    brand: 'EcoWear',
    rating: 4.8,
    reviews: 250,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Blanc', hex: '#FFFFFF' },
      { name: 'Noir', hex: '#000000' },
      { name: 'Gris Chiné', hex: '#9E9E9E' },
    ],
    isNew: false,
    onSale: true,
    salePrice: 15000,
  },
  {
    id: 'prod_003',
    name: 'Jean skinny taille haute',
    description: "Ce jean skinny épouse vos formes pour une silhouette flatteuse. Sa taille haute et sa matière extensible offrent confort et style.",
    price: 32000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757878/allano-app/high-waist-skinny-jeans_w3z5ml.jpg', 'https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757878/allano-app/high-waist-skinny-jeans-2_n2t8rv.jpg'],
    category: 'Vêtements',
    subcategory: 'Jeans',
    brand: 'Denim & Co',
    rating: 4.3,
    reviews: 85,
    sizes: ['36', '38', '40', '42'],
    colors: [
      { name: 'Bleu Brut', hex: '#000080' },
      { name: 'Noir Délavé', hex: '#343434' },
    ],
    isNew: true,
  },
  {
    id: 'prod_004',
    name: 'Baskets de ville en cuir',
    description: "Des baskets élégantes et polyvalentes, parfaites pour compléter n'importe quelle tenue décontractée. Fabriquées en cuir véritable pour une durabilité accrue.",
    price: 45000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757878/allano-app/leather-city-sneakers_vbl7pm.jpg', 'https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/leather-city-sneakers-2_pdxwub.jpg'],
    category: 'Chaussures',
    subcategory: 'Baskets',
    brand: 'Urban Kicks',
    rating: 4.7,
    reviews: 150,
    sizes: ['39', '40', '41', '42', '43'],
    colors: [
      { name: 'Blanc', hex: '#FFFFFF' },
      { name: 'Noir', hex: '#000000' },
    ],
    isNew: false,
    onSale: true,
    salePrice: 38000,
  },
  {
    id: 'prod_005',
    name: 'Sac à main structuré',
    description: "Un sac à main chic et structuré qui ajoute une touche d'élégance à votre look. Assez spacieux pour tous vos essentiels.",
    price: 28000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/structured-handbag_f0kysk.jpg', 'https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/structured-handbag-2_avwywp.jpg'],
    category: 'Sacs',
    subcategory: 'Sacs à main',
    brand: 'Elara',
    rating: 4.6,
    reviews: 95,
    sizes: ['Unique'],
    colors: [
      { name: 'Noir', hex: '#000000' },
      { name: 'Beige', hex: '#F5F5DC' },
    ],
    isNew: true,
  },
  {
    id: 'prod_006',
    name: 'Sandales en cuir',
    description: "Des sandales confortables et stylées pour l'été. Fabriquées en cuir véritable avec une semelle souple.",
    price: 18000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/leather-sandals_fl3hrc.jpg'],
    category: 'Chaussures',
    subcategory: 'Sandales',
    brand: 'Allano Chic',
    rating: 4.4,
    reviews: 70,
    sizes: ['38', '39', '40', '41'],
    colors: [{ name: 'Marron', hex: '#8B4513' }],
    isNew: false,
  },
  {
    id: 'prod_007',
    name: 'Chemise en lin',
    description: "Une chemise légère et respirante en lin, parfaite pour les climats chauds. Un look décontracté mais élégant.",
    price: 22000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/linen-shirt_kgdrlj.jpg'],
    category: 'Vêtements',
    subcategory: 'Chemises',
    brand: 'Allano Chic',
    rating: 4.6,
    reviews: 110,
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Blanc', hex: '#FFFFFF' },
      { name: 'Bleu ciel', hex: '#87CEEB' },
    ],
    isNew: true,
  },
  {
    id: 'prod_008',
    name: 'Collier pendentif doré',
    description: "Un collier délicat avec un pendentif circulaire, plaqué or. Parfait pour ajouter une touche de brillance à votre quotidien.",
    price: 15000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/gold-pendant-necklace_sznwl6.jpg'],
    category: 'Bijoux',
    subcategory: 'Colliers',
    brand: 'Aura',
    rating: 4.9,
    reviews: 180,
    sizes: ['Unique'],
    colors: [{ name: 'Or', hex: '#FFD700' }],
    isNew: false,
  },
  {
    id: 'prod_009',
    name: 'Ensemble T-shirt et short pour enfant',
    description: "Un ensemble mignon et confortable pour les enfants, idéal pour jouer toute la journée. 100% coton.",
    price: 12000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757880/allano-app/kids-tshirt-short-set_pzwjyr.jpg'],
    category: 'Enfants',
    subcategory: 'Ensembles',
    brand: 'Allano Kids',
    rating: 4.8,
    reviews: 60,
    sizes: ['2A', '4A', '6A'],
    colors: [{ name: 'Bleu marine', hex: '#000080' }],
    isNew: true,
  },
  {
    id: 'prod_010',
    name: 'Chapeau de paille',
    description: "Le compagnon idéal pour vos journées à la plage ou vos balades en ville. Protège du soleil avec style.",
    price: 8500,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/straw-hat_xagqav.jpg'],
    category: 'Chapeaux',
    subcategory: 'Chapeaux de paille',
    brand: 'Allano Chic',
    rating: 4.6,
    reviews: 45,
    sizes: ['Unique'],
    colors: [{ name: 'Naturel', hex: '#DEB887' }],
    isNew: false,
    onSale: true,
    salePrice: 7000,
  },
  {
    id: 'prod_011',
    name: 'Lunettes de soleil Aviateur',
    description: "Un classique intemporel. Ces lunettes de soleil aviateur offrent une protection UV à 100% et un style inégalé.",
    price: 17000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757879/allano-app/aviator-sunglasses_qtnpba.jpg'],
    category: 'Accessoires',
    subcategory: 'Lunettes',
    brand: 'Sunnies',
    rating: 4.7,
    reviews: 90,
    sizes: ['Unique'],
    colors: [{ name: 'Noir', hex: '#000000' }],
    isNew: false,
  },
  {
    id: 'prod_012',
    name: 'Ceinture en cuir tressé',
    description: "Une ceinture polyvalente en cuir tressé qui s'adapte parfaitement à un jean ou un pantalon chino.",
    price: 13000,
    images: ['https://res.cloudinary.com/dhjcx6ckx/image/upload/v1721757878/allano-app/braided-leather-belt_hdz3t8.jpg'],
    category: 'Accessoires',
    subcategory: 'Ceintures',
    brand: 'Denim & Co',
    rating: 4.5,
    reviews: 55,
    sizes: ['85cm', '95cm', '105cm'],
    colors: [{ name: 'Marron foncé', hex: '#5C4033' }],
    isNew: false,
  }
];
