
import type { Product } from './types';

export const PRODUCTS: Product[] = [
  // Vêtements
  {
    id: 'prod_v_001',
    name: "Pull over",
    description: "Un pull over confortable et stylé, parfait pour les soirées fraîches. Tissu doux et coupe moderne.",
    price: 22000,
    images: ['vetements/pull-over'],
    category: 'Vêtements',
    brand: 'Allano Wear',
    rating: 4.6,
    reviews: 88,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [ { name: 'Gris', hex: '#808080' }, { name: 'Noir', hex: '#000000' } ],
    isNew: true,
  },
  {
    id: 'prod_v_002',
    name: "Tee shirt",
    description: "Le t-shirt basique indispensable. Confortable, durable et facile à associer. 100% coton.",
    price: 9000,
    images: ['vetements/tee-shirt'],
    category: 'Vêtements',
    brand: 'Allano Basic',
    rating: 4.8,
    reviews: 150,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [ { name: 'Blanc', hex: '#FFFFFF' }, { name: 'Noir', hex: '#000000' } ],
    isNew: true,
  },
  // Chaussures
  {
    id: 'prod_c_001',
    name: "Claquettes Benassi Nike",
    description: "Les claquettes Nike Benassi offrent un confort léger dans un design classique.",
    price: 18000,
    images: ['chaussures/claquettes-nike'],
    category: 'Chaussures',
    brand: 'Nike',
    rating: 4.9,
    reviews: 210,
    sizes: ['40', '41', '42', '43', '44'],
    colors: [ { name: 'Noir', hex: '#000000' } ],
    isNew: true,
  },
  {
    id: 'prod_c_002',
    name: "Claquettes Jordan",
    description: "Style et confort décontracté avec les claquettes Jordan, parfaites après le match ou pour la ville.",
    price: 25000,
    images: ['chaussures/claquettes-jordan'],
    category: 'Chaussures',
    brand: 'Jordan',
    rating: 4.8,
    reviews: 180,
    sizes: ['40', '41', '42', '43', '44'],
    colors: [ { name: 'Rouge', hex: '#FF0000' }, { name: 'Noir', hex: '#000000' } ],
  },
  {
    id: 'prod_c_003',
    name: "Claquettes Under Armour",
    description: "Confort inégalé avec la semelle en mousse des claquettes Under Armour.",
    price: 22000,
    images: ['chaussures/claquettes-under-armour'],
    category: 'Chaussures',
    brand: 'Under Armour',
    rating: 4.7,
    reviews: 130,
    sizes: ['40', '41', '42', '43', '44'],
    colors: [ { name: 'Noir', hex: '#000000' } ],
  },
  {
    id: 'prod_c_004',
    name: "Air Force 1",
    description: "L'icône du basketball réinventée pour la rue. La Nike Air Force 1 est une légende.",
    price: 65000,
    images: ['chaussures/air-force-1'],
    category: 'Chaussures',
    brand: 'Nike',
    rating: 5,
    reviews: 550,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: [ { name: 'Blanc', hex: '#FFFFFF' } ],
    isNew: true,
  },
  {
    id: 'prod_c_005',
    name: "Air Jordan 1",
    description: "La chaussure qui a tout commencé. Style intemporel et confort au quotidien.",
    price: 95000,
    images: ['chaussures/air-jordan-1'],
    category: 'Chaussures',
    brand: 'Jordan',
    rating: 4.9,
    reviews: 480,
    sizes: ['40', '41', '42', '43', '44'],
    colors: [ { name: 'Chicago', hex: '#CD212A' } ],
    onSale: true,
    salePrice: 85000,
  },
  {
    id: 'prod_c_006',
    name: "Crocs",
    description: "Le confort ultime pour vos pieds. Légères, fun et faciles à nettoyer.",
    price: 30000,
    images: ['chaussures/crocs'],
    category: 'Chaussures',
    brand: 'Crocs',
    rating: 4.5,
    reviews: 320,
    sizes: ['38', '39', '40', '41', '42'],
    colors: [ { name: 'Bleu', hex: '#0000FF' }, { name: 'Rose', hex: '#FFC0CB' } ],
  },
  // Sacs
  {
    id: 'prod_s_001',
    name: "Tote bag",
    description: "Le sac fourre-tout simple et pratique pour vos courses ou vos sorties.",
    price: 7500,
    images: ['sacs/tote-bague'],
    category: 'Sacs',
    brand: 'Allano Basic',
    rating: 4.4,
    reviews: 95,
    sizes: ['Unique'],
    colors: [ { name: 'Beige', hex: '#F5F5DC' } ],
  },
  {
    id: 'prod_s_002',
    name: "Sacoche Nike",
    description: "Une sacoche compacte et durable pour garder vos essentiels à portée de main.",
    price: 19000,
    images: ['sacs/sacoche-nike'],
    category: 'Sacs',
    brand: 'Nike',
    rating: 4.8,
    reviews: 160,
    sizes: ['Unique'],
    colors: [ { name: 'Noir', hex: '#000000' } ],
    isNew: true,
  },
  {
    id: 'prod_s_003',
    name: "Sacoche Adidas",
    description: "Style iconique à trois bandes. La sacoche Adidas est parfaite pour un look sportif.",
    price: 18000,
    images: ['sacs/sacoche-adidas'],
    category: 'Sacs',
    brand: 'Adidas',
    rating: 4.7,
    reviews: 145,
    sizes: ['Unique'],
    colors: [ { name: 'Noir', hex: '#000000' } ],
  },
  {
    id: 'prod_s_004',
    name: "Sac à dos Nike",
    description: "Spacieux et résistant, ce sac à dos Nike est idéal pour le sport, l'école ou le quotidien.",
    price: 28000,
    images: ['sacs/sac-a-dos-nike'],
    category: 'Sacs',
    brand: 'Nike',
    rating: 4.9,
    reviews: 200,
    sizes: ['Unique'],
    colors: [ { name: 'Noir', hex: '#000000' } ],
    onSale: true,
    salePrice: 25000,
  },
  // Bijoux
  {
    id: 'prod_b_001',
    name: "Montre Casio",
    description: "La montre Casio vintage, un accessoire rétro-chic indémodable.",
    price: 25000,
    images: ['bijoux/montre-casio'],
    category: 'Bijoux',
    brand: 'Casio',
    rating: 4.8,
    reviews: 300,
    sizes: ['Unique'],
    colors: [ { name: 'Argent', hex: '#C0C0C0' }, { name: 'Or', hex: '#FFD700' } ],
  },
  {
    id: 'prod_b_002',
    name: "Montre Hublot Genève",
    description: "L'art de la fusion. Une montre de luxe qui allie matériaux innovants et savoir-faire horloger.",
    price: 4500000,
    images: ['bijoux/montre-hublot'],
    category: 'Bijoux',
    brand: 'Hublot',
    rating: 5,
    reviews: 25,
    sizes: ['Unique'],
    colors: [ { name: 'Noir Céramique', hex: '#343434' } ],
  },
  {
    id: 'prod_b_003',
    name: "Apple Watch Series 10",
    description: "Votre santé au poignet. L'Apple Watch Series 10 est plus intelligente et plus robuste que jamais.",
    price: 350000,
    images: ['bijoux/apple-watch-s10'],
    category: 'Bijoux',
    brand: 'Apple',
    rating: 4.9,
    reviews: 450,
    sizes: ['46mm'],
    colors: [ { name: 'Minuit', hex: '#1C1C1E' } ],
    isNew: true,
  },
  {
    id: 'prod_b_004',
    name: "Boucle d’oreille aimantée",
    description: "Le style sans la douleur. Des boucles d'oreilles élégantes et discrètes maintenues par un aimant.",
    price: 5000,
    images: ['bijoux/boucle-oreille'],
    category: 'Bijoux',
    brand: 'Allano Style',
    rating: 4.3,
    reviews: 110,
    sizes: ['Unique'],
    colors: [ { name: 'Argent', hex: '#C0C0C0' } ],
  },
  // Chapeaux
  {
    id: 'prod_ch_001',
    name: "Casquette Nike",
    description: "Une casquette de sport classique avec le logo emblématique. Tissu anti-transpiration.",
    price: 15000,
    images: ['chapeaux/casquette-nike'],
    category: 'Chapeaux',
    brand: 'Nike',
    rating: 4.7,
    reviews: 250,
    sizes: ['Unique'],
    colors: [ { name: 'Noir', hex: '#000000' }, { name: 'Blanc', hex: '#FFFFFF' } ],
  },
  {
    id: 'prod_ch_002',
    name: "Casquette Adidas",
    description: "La casquette parfaite pour un look décontracté, avec les 3 bandes signatures.",
    price: 14000,
    images: ['chapeaux/casquette-adidas'],
    category: 'Chapeaux',
    brand: 'Adidas',
    rating: 4.6,
    reviews: 230,
    sizes: ['Unique'],
    colors: [ { name: 'Noir', hex: '#000000' } ],
  },
  // Accessoires
  {
    id: 'prod_a_001',
    name: "Luxe scrunchie",
    description: "Un chouchou en soie ou en velours pour attacher vos cheveux avec élégance et sans les abîmer.",
    price: 4000,
    images: ['accessoires/luxe-scrunchie'],
    category: 'Accessoires',
    brand: 'Allano Beauty',
    rating: 4.8,
    reviews: 90,
    sizes: ['Unique'],
    colors: [ { name: 'Rose', hex: '#FFC0CB' }, { name: 'Bordeaux', hex: '#800000' } ],
    isNew: true,
  },
  {
    id: 'prod_a_002',
    name: "Hair clips",
    description: "Pinces à cheveux tendances pour maintenir vos mèches avec style.",
    price: 3000,
    images: ['accessoires/hair-clips'],
    category: 'Accessoires',
    brand: 'Allano Beauty',
    rating: 4.5,
    reviews: 75,
    sizes: ['Unique'],
    colors: [ { name: 'Or', hex: '#FFD700' } ],
  },
  {
    id: 'prod_a_003',
    name: "Scrunchies",
    description: "Lot de chouchous colorés pour varier les plaisirs et accessoiriser toutes vos tenues.",
    price: 5000,
    images: ['accessoires/scrunchies'],
    category: 'Accessoires',
    brand: 'Allano Beauty',
    rating: 4.6,
    reviews: 120,
    sizes: ['Lot de 5'],
    colors: [ { name: 'Multicolore', hex: '#FFFFFF' } ],
    onSale: true,
    salePrice: 3500,
  },
  {
    id: 'prod_a_004',
    name: "Masque de visage hydratant",
    description: "Offrez un bain d'hydratation à votre peau avec ce masque en tissu.",
    price: 2500,
    images: ['accessoires/masque-visage'],
    category: 'Accessoires',
    brand: 'Beauty Care',
    rating: 4.9,
    reviews: 180,
    sizes: ['Unique'],
    colors: [ { name: 'Transparent', hex: '#FFFFFF' } ],
  },
  {
    id: 'prod_a_005',
    name: "Brume parfumée",
    description: "Une brume légère pour le corps et les cheveux, pour une touche de fraîcheur parfumée tout au long de la journée.",
    price: 8000,
    images: ['accessoires/brume-parfumee'],
    category: 'Accessoires',
    brand: 'Scent & Co',
    rating: 4.7,
    reviews: 130,
    sizes: ['100ml'],
    colors: [ { name: 'Fleur de cerisier', hex: '#FFB7C5' } ],
  },
  {
    id: 'prod_a_006',
    name: "Lunettes de soleil",
    description: "Un classique intemporel. Ces lunettes de soleil offrent une protection UV à 100% et un style inégalé.",
    price: 17000,
    images: ['accessoires/lunettes-de-soleil'],
    category: 'Accessoires',
    brand: 'Sunnies',
    rating: 4.7,
    reviews: 90,
    sizes: ['Unique'],
    colors: [{ name: 'Noir', hex: '#000000' }],
    isNew: false,
  }
];
